version: "3.9"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: "tgbot"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"